services:

  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: guacamole
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: guacamole
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    - data:/var/lib/postgresql/data

  guacd:
    image: guacamole/guacd
    volumes:
    - drive:/drive
    - record:/record

  guacamole:
    image: guacamole/guacamole
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: db
      POSTGRES_DATABASE: guacamole
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: guacamole
    depends_on:
    - guacd
    - db

  proxy:
    image: nginx
    ports:
    - 8080:8080
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./cers:/etc/nginx/certs
    depends_on:
    - auth
    - guacamole

volumes:
  data:
  drive:
  record:
